"""init

Revision ID: 3006e6dd7b71
Revises: bb0b53d33e4d
Create Date: 2022-09-09 11:29:59.682265

"""

# revision identifiers, used by Alembic.
revision = '3006e6dd7b71'
down_revision = 'bb0b53d33e4d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
