"""init

Revision ID: 69e39c6210bc
Revises: 3006e6dd7b71
Create Date: 2022-09-11 20:51:40.378699

"""

# revision identifiers, used by Alembic.
revision = '69e39c6210bc'
down_revision = '3006e6dd7b71'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
