"""init

Revision ID: bb0b53d33e4d
Revises: dd33cb03d01f
Create Date: 2022-09-09 10:56:47.815518

"""

# revision identifiers, used by Alembic.
revision = 'bb0b53d33e4d'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
